# Generated by Django 5.0.3 on 2024-04-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='12345678', max_length=20),
        ),
    ]
